name: app_todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_emoji: ^2.5.1
  date_picker_timeline: ^1.2.5
  timeago: ^3.6.1
  toastification: ^1.2.1
  flutter_advanced_drawer: ^1.3.6
  uuid: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/